steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/survey-dev-8bc44/survey-app-backend:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/survey-dev-8bc44/survey-app-backend:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
# NOTE 地區選在台灣
  args: ['run', 'deploy', 'survey-app-backend',
         '--image', 'gcr.io/survey-dev-8bc44/survey-app-backend:$COMMIT_SHA',
         '--region', 'asia-east1', '--platform', 'managed']
  env:
    - 'ENV=dev'
images:
- 'gcr.io/survey-dev-8bc44/survey-app-backend:$COMMIT_SHA'